### PR TITLE
Scripted releases to NPM

### PR DESCRIPTION
**Pull request by kevgo**
@alexdavid @charlierudolph @bentona 

Release script for fully automated and super error checked releases to NPM!

I finally figured out an (admittedly super hacky) way to have the correct JS binary version in the commit that carries the tag, dammit!

__old problematic way__
* `npm publish` bumps the version in `package.json`, and creates a Git tag
* `npm run compress` reads package.json for the version
* this means I could only compile the new binary after the version was bumped 
* this means the tagged commit has the old JS binary

__Solution__
* parse old version out of package.json using grep
* determine new version using `semver -i patch 0.0.1`
* compile the JS binary 
* replace old version in JS binary with new version
* commit JS binary
* bump NPM version

### CODE REVIEW

**Comment by charlierudolph** [comment]
Uncertain if this would be less hacky but you could use the `--no-git-tag-version` option which won't commit or tag. See [here](https://docs.npmjs.com/cli/version) for more details. Then you could run `npm version`, make the build, and then commit and tag is yourself.

**Comment by charlierudolph** [comment]
With all the complex logic you are doing I would also suggest writing this in coffeescript with [shelljs](https://github.com/arturadib/shelljs).

**Comment by kevgo** [comment]
Thanks for the awesome feedback @charlierudolph! `--no-git-tag-version` sounds like a great idea, thanks! I think I'll go that route. Regarding a rewrite in CoffeeScript, I'm a bit hesitant. I'm unsure if that actually would end up being much simpler, and I don't really get the point of shelljs. Let me take another stab at simplifying the Bash version before I give up on that stack here.

**Comment by charlierudolph** [comment]
You could use the `exec` command of `shelljs` to run the git commands.

**Pull request closed without merging**
